// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wahiivkcixmfrytxehaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhaGlpdmtjaXhtZnJ5dHhlaGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTAxNDYsImV4cCI6MjA3MzA2NjE0Nn0.AN06mmQfwSaN0nu0ZHmsSwpslSpoPQNIlNUawd8uqw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});